### ISSUE TITLE
100% CPU when mining Feathercoin

### ISSUE THREAD

**Issue by pilotniq** [ghostlander/ccminer-neoscrypt#1]
I'm getting 100% CPU use when running against Feathercoin version v0.9.3.2-ftcit-Standard (2016-07-24 10:16:27 +0200)

./ccminer -a neoscrypt -o http://172.16.1.23:9337 -O feathercoinrpc:_password_
Compiled with GCC 5.4 using Nvidia CUDA Toolkit 7.5

[2016-08-30 00:59:23] NVML GPU monitoring enabled.
[2016-08-30 00:59:23] 1 miner thread started, using 'neoscrypt' algorithm.
[2016-08-30 00:59:23] Binding thread 0 to cpu 0 (mask 1)
[2016-08-30 01:00:16] GPU #0: GeForce GTX 970, 707 (T= 67C F= 37% C=1470/3004)

I've previously used https://github.com/djm34/ccminer-sp-neoscrypt.git which does not have the 100% CPU problem, but can't talk to feathercoind version 0.9 because of some part of the network protocol it doesn't understand.

**Comment by ghostlander** [comment]
Yes, it 100% loads one CPU core per every GPU thread. I haven't investigated it much, but I see the same issue on NVIDIA with OpenCL.

My fork supports Getwork, therefore it can be used for solo mining.
