### ISSUE TITLE
Build error on Debian 9.1 64-bit

### ISSUE THREAD

**Issue by gkozin** [ghostlander/ccminer-neoscrypt#2]
`/usr/bin/ld:` neoscrypt/neoscrypt.o: relocation R_X86_64_32S against symbol `device_map' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: neoscrypt/cuda_neoscrypt.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:539: recipe for target 'ccminer' failed
make[2]: *** [ccminer] Error 1`

**Comment by ghostlander** [comment]
If you build shared libraries, it's quite obvious to compile with -fPIC. However static ones work just fine.
